WebClub-NITK/Hacktoberfest-2k17

Participants/VithikShah.txt
=> Vithik Shah details added

Participants/Shreyanshnit19.txt
=> Shreyansh Sancheti Details added

Participants/raunak-batar.txt
=> RAUNAK BATAR DETAILS added

Participants/nimish-04.txt, a.txt
=> nimish-04 details added

Participants/Hyper_Act-Details.txt
=> Hyper-Act Details added

Participants/adarshj17.txt
=> Adarsh Jha details added

Participants/vachhanihpavan.txt
This Pull Request resolves Issue #1  
Description:
Added Participant details
=> Resolved #1

Participants/madhuparna04.txt
=> madhuparna04

participants/file.txt.txt
=> file added: apeksha

BubbleSort/suraj44.py, Participants/suraj44.txt
Description:
Added file suraj44.txt to Participants folder
=> Adding suraj44 participant details

Participants/salman-bhai.txt
* First Pull Request to Web Club NITK for Hacktoberfest 2k17 added!
* This Pull Request resolves Issue #1
* Admins do not merge this PR as of now!
=> User Description for salman-bhai added

Insertion_Sort/archit-p.c, Participants/archit-p.txt, Quick_Sort/archit-p.c
This Pull Request resolves Issue #1 and #13 
Description:
Added a new directory called Insertion_Sort
=> Added insertion sort in c and details for archit-p

participants/rahul.txt
This Pull Request resolves Issue #
Description:
=> Rahul details added

Participants/Faziludupi.txt
=> FazilUdupi details

Participants/navy1999.txt
=> navy1999 details added

participants/patilprajwal.txt
This Pull Request resolves Issue 1
Description:
=> prajwal pohekar details added

Participants/kuldeep.txt
=> first commit

Participants/Jahnwee.txt, helloworld.c.txt
=> Jahnwee mca

Participants/Jahnwee.txt
=> Jahnwee Details Added

Participants/basithnitk.txt
=> Abdul Basith Ashraf details added

C/Vishal3103.c, Participants/Vishal.txt
Description:
In this Pull Request we have done the following additions/edits for the code: Printed Hello world using C
=> Vishal3103

Participants/Vishal.txt
Description:
In this Pull Request we have done the following additions/edits for the code: First pull request
=> First commit on Hacktoberfest

Insertion_Sort/ashwin_joisa.c
=> Insertion Sort

Quick_Sort/ashwin_joisa.c
=> Quick Sort

Participants/sharanyakamath.txt, sharanyakamath/seive_of_erastothenes.cpp
This pull request resolves issue #17 and issue #1
=> Implement Sieve of Erastothenes

Fibonacci_Search/ashwin_joisa.c
This Pull Request resolves Issue #19 
Fourth PR
=> Fibonacci Search

Participants/katakuri1239.txt
=> Shravan is a op fan

participants/mickey4190.txt
=> mickey4190 details added

Participants/RosaGeorge31
First Pull Request to Web Club NITK for added!
This pull request solves Issue #1
=> User Description for Rosa added

Participants/riyajagtap.txt
=> riyajagtap details added

Participants/manas11.txt
=> Manas details added

Participants/isunitha98selvan.txt
=> Sunitha details added

Participants/Manask322.txt
=> Manas Kinkar Details added

Participants/chaitany10.txt
=>  Chaitany Pandiya details added

Participants/shanthanu9.txt
=> Shanthanu Details added

Participants/saurabh.txt
Description:
Saurabh added details
=> Saurabh details added

Insertion_Sort/ankitsvt11.c, Python/ankitsvt11.py
=> Anki patch

Insertion_Sort/ankitsvt11.c, Python/ankitsvt11.py
=> Ankit patch

BITWISE_operators/Z0Marlin.c, Participants/aditya-jain.txt, Python/Z0Marlin.py, Reverse_String/Z0Marlin.c
This Pull Request resolves Issue #9
Description:
Added code to reverse a string.
=> Reverse String

Participants/aditya-jain.txt, Python/Z0Marlin.py
This Pull Request resolves Issue #1 and #11 
Description:
I have added my details and added code for hello world program in python
=> Aditya details added

issue.py
=> Simple Calculator in python using if elif

quicksort.c
Description:
c program for quicksort
=> quicksort in c

quicksort.c, sieve.c
This Pull Request resolves Issue #17 
Description:
implementation of sieve of eratosthenes
=> sieve of eratosthenes

Participants/karanmohadikar.txt
=> Files added

participants/nisargJoshi.txt
=> Nisarg Joshi Details added

Participants/SIDX123111104130.txt, Python/SIDX123111104130.py
=> Siddhant Saraswat Details added

Participants/ankitgaur17.txt
=> ankit gaur details added

Participants/joshua.txt
=> Added Joshua's details

participants/rjshubh.txt
Description:i added participant details
=> shubh details added

BubbleSort/madhuparna04.c
=> BubbleSort.c

Participants/pramathabhat.txt, pramathabhat.c
This Pull Request resolves Issue #25
Description:
=> Solving add binary search issue

participants/arvind97.txt
Description:
In this Pull Request, I have inserted my details.
=> Inserted Details in participants/arvind97.txt

Merge_Sort/Arunraj97.cpp, Participants/Arunraj97.txt
=> User Description for Arunraj added

Participants/hardikran.txt.txt
This Pull Request resolves #1 
Description:
=> hardik rana details added

Participants/Avinash.txt
=> Avinash Details added

Quick_Sort/sharanyakamath.cpp
Description:
In this pull request I have added Quick sort program in C.
It is stored as sharanyakamath.c in folder Quick_Sort
=> Added quick sort

BubbleSort/arvind97.cpp
Description:
In this Pull Request, I have implemented BubbleSort in C++.
=> Arvind97.patch2

Python/arc999.py, participants/arc999.txt
=> Archit Detals added

Python/arc999.py, participants/arc999.txt
=> Python file added

C/Rakeshpavan333.c
=> Rakesh Pavan Hello World C

Participants/shivampotdar99.txt
=> Shivam Potdar Details added

Participants/SurajV7.txt
=> Suraj V details added

Participants/salman-bhai.txt, Python/salman-bhai.py
=> Salman shah patch

Participants/Anish1207.txt.txt
=> anish patil details

Participants/rohitkhoja.txt
=> rohit khoja details added

participants/animesh.txt
This Pull Request resolves Issue #
Description:
=> Animesh Kumar Details Added

Participants/test.txt
=> Details added by me

Participants/AB261.txt
Description:
Added participant details for AB261
=> Added participant information

Poojitha
=> Poojitha  details added

participants/sarthakc0806.txt
=> Sarthakc pull request

participants/srinskit
=> Sriskit's pull req

Participants/vsushruth.txt
Description:I have added my details
=> Sushruth V Details added

Participants/Pranav.txt
=> File added

Participants/span09..txt
=> Spandana Details added

Participants/jvsriharsha.txt
=> J V Sriharsha details added

Participants/anujkhuranaa.txt
=> AnujKhurana

Participants/itsdarren007.txt
=> Darren Charles details added

Fibonacci_Search/RosaGeorge31.c, Participants/RosaGeorge31
This Pull Request resolves Issue #19  #1 
Description:
Fibonacci Search Code added
=> Fibonacci Search by Rosa added

C/shanthanu9.c, Participants/shanthanu9.txt, Python/Hello_world.py
This Pull Request resolves Issue #1 #3 #11 
Description:
=> Shanthanu9 patch

Participants/17aakashsingh1999.txt, c/hello.c
=> 17aakashsingh1999 details added

BitwiseOperator/parth.py, Participants/parth.txt
This Pull Request resolves Issue #28 #1 
Description:
=> Parth patch

BitwiseOperator/parth.py, Participants/parth.txt
=> Parth Shah details added

participants/akshit.txt
=> Akshit Patel Details added

Participants/ashwathbhat.txt
=> Details Added

Participants/hlpr98.txt
Description:
User Description added
=> User Description for Praveen Raj added

Participants/arqum.txt
=> Arqum Shaikh Details added

Participants/PSL14.txt
=> Pratik Lohiya details added

Participants/akshay.txt, Python/AkshaySharma-Akay.py
This Pull Request resolves Issue #1 #11 
Description:
In this Pull Request we have done the following additions/edits for the code:(First Pull request)
=> First Commit on Hacktoberfest 2k17

Python/anmoljindal13.py, participants/anmoljindal13.txt
This Pull Request resolves Issue #11 #1 
Description:
Added Hello World in Python
=> Anmoljindal13 patch

c/rjshubh.c, participants/rjshubh.txt, python/rjshubh.py
This Pull Request resolves Issue #11 #1 #3 
Description:added hello world in python
=> Rjshubh patch

Participants/katakuri1239.txt, hello.c
This Pull Request resolves Issue #9 #1 
Description:
=> Katakuri c

C/AkshaySharma-Akay.c, Participants/akshay.txt, Python/AkshaySharma-Akay.py
This Pull Request resolves Issue #3 #1 #11 
Description:
Added the Hello World Program Using C Language.
=> Akshay sharma akay

PSL14/sieve_of_erastothenes.cpp, Participants/PSL14.txt, Quick_Sort/PSL14.cpp
This Pull Request resolves Issue #24 #1 #30  
Description:
=> Pratik lohiya patch

C/navy1999.c
=> added hello world

C/Hyper-Act.c
=> Hello world program

Participants/hello word.c, Participants/nikita.txt
This Pull Request resolves Issue #1 #3 
Description:
=> nikita gurjar maktapur

Participants/SrivatsanV.txt
=> SrivatsanV details added

participants/asha.txt
=> added new file

Participants/Yogesh.txt
=> Added yogesh

Participants/subhash7380.txt
=> subhash details added

c/Asmanjas.c, paticipants/Asmanjas.txt
This Pull Request resolves Issue #1 #3 
Description:
=> Asmanjas Details added

C/anujkhuranaa.c, Participants/anujkhuranaa.txt
This Pull Request resolves Issue #3 #1
=> Anujkhuranaa patch

participants/nisargJoshi.txt, python/NJnisarg.py
This Pull Request resolves Issue #11 #1 
Description:
=> Testing branch

Insertion_Sort/VaishnaviMishra.py, Python/BST.py
This Pull Request resolves Issue #13  #1 
Description:
added python code
=> python code for insertion sort

Binary Search/bs.txt.txt, Participants/Anish1207.txt.txt
This Pull Request resolves Issue #25 
Description:
=> Anishbinary

BubbleSort/arvind97.cpp, Python/arvind97.py
This Pull Request resolves Issue #156 and #27 
Description:
In this Pull Request, I have implemented a python program to display "Hello, World!" and also a c++ program to carry out BubbleSort.
=> Arvind97.patch3

BubbleSort/ankitgaur17.cpp, Participants/ankitgaur17.txt, ankitgaur17/sieve_of_erastothenes.cpp
=> Ankit gaur patch

Participants/deepeshagarawal.txt
=> Deepesh information added

Participants/AmanP.txt
First Pull Request to Web Club NITK for Hacktoberfest 2k17 added 
=> User description for illseption added

Poojitha.py
=> Poojitha-patch

C/karanmohadikar.c, Hello_Web/karanmohadikar.html, Participants/karanmohadikar.txt, Python/python.py.txt
=> Karanmohadikar

C/karanmohadikar.c, Hello_Web/karanmohadikar.html, Participants/karanmohadikar.txt, Python/python.py.txt
=> Karanmohadikar patch

Hello_Web/illseption.html
This Pull Request resolves Issue #22 
Description:
In this Pull Request I have done the following additions for the code:
- Created a simple page with a button
- On clicking the button, "Hello world!" is displayed
- Used basic javascript and html 
Please review
=> Implement Simple Hello World Page

Insertion_Sort/hardikran.c, Participants/hardikran.txt.txt
This Pull Request resolves Issue #13
Description:
added folder Insertion_Sort
added hardikran.c
=> Solved Insertion_Sort Issue

Participants/nishanthebbar.txt, nishanthebbar.txt, nishanthebbar/ne
This Pull Request resolves Issue #4
=> Menu driven calculator

Participants/ravi.txt, c/hello.c
This Pull Request resolves Issue #1 #3 
Description:
=> Ravi details added

Python/utkarsh23.py
=> Hello World python - utkarsh23 patch

Insertion_Sort/arc999.cpp, arc999/sieve_of_erastothenes.cpp
This Pull Request resolves Issue #17 #16 
Description:
1) Implemented sieve of eratosthnes
2) Implemented insertion sort
=> Implement Sieve of Eratosthenes

Participants/insertion-sort.c
=> Added Insertion Sort

C/Mukesh-BR.c
=> Hello world 

C/tanmai-h.c
printing hello world in C.
Solves Issue #3
=> Hello World in C

C++/README.md, C++/compare-numeric-string.cc
C++ program to compare two number string.
=> Compare two number string

bitwise /ArqumShaikh.c
This Pull Request resolves Issue #28 
Description:
Basic program on how to use bitwise operators
=> Implementation of Bitwise Operators

C/bharm1.c
=> Added bharm1.c (hello, world! in c)

C/SrivatsanV.c.txt, Python/SrivatsanV.py.txt
This Pull Request resolves Issue #11 #3 
Description:
In this Pull Request we have done the following additions/edits for the code:Printed Hello World in python
=> hello world in python

C/anmoljindal13.c, Python/anmoljindal13.py, participants/anmoljindal13.txt
This Pull Request resolves Issue #1 #3 #11 
Description:
Added participant details
=> Anmol Jidal Details added

participants/Rhevanth.txt
Description: This are my details
This solves #1 for Participants details.
=> rhevanth details added

participants/akshit.txt, python/akshitpatel01.py.txt
This Pull Request resolves Issue #11 #1 
Description:
=> Hello World in Python and Participant Details

Quick_Sort/DhvanilP.c
=> Quick_Sort added 

participants/oneiroi333.txt
* First Pull Request to Web Club NITK for Hacktoberfest 2k17 added
* This Pull Request solves Issue #1
=> User description for oneiroi333 added

Participants/Ishaan0905.txt
=> User info added for Ishaan0905

C/Ishaan0905.c, Python/Ishaan0905.py
This Pull Request resolves Issue #3  and #11  
Description:
Added C program to print Hello World
Added Py program to print Hello World
=> Solved issues #3(C) and#11(Py)

BitwiseOperator/Ishaan0905.py
This Pull Request resolves Issue #28 
Description:
Added Bitwise operator program in Python
=> Added Bitwise operator program in Python #28

C/AkshaySharma-Akay.c, Insertion Sort/AkshaySharma-Akay.c, Participants/akshay.txt, Python/AkshaySharma-Akay.py
This Pull Request resolves Issue #13 #11 #3 #1
Description:
=> New akshay sharma akay

Participants/ravi.txt, c/hello.c, c/ravijohnmark.c, html/ravijohnmark.html, string/string.c
This Pull Request resolves Issue #9 #1 #14
=> Hello World in different languages!

Bubble_Sort/adarshj17.c, C/adarshj17.c, C/hello.c, Insertion_Sort/adarshj17.c, Python/adarshj17.py
This Pull Request resolves Issue #27 #11
=> Phirle patch

C/radhe14341.c
=> Added suggested C Folder

C/reverse_string.c
This Pull Request resolves Issue #9 
Description:
=> Added the reverse string program

Python/dobby33.py
=> Added hello world by dobby33

Quick_Sort/geekgeekvm.py
Description:
Implemented quick sort recursively in Python
=> Python imlementation for quick sort

BubbleSort/nishanthebbar2011.py
This Pull Request resolves Issue #27 Bubble Sort
=> Bubble sort added

PARTICIPANTS/leonardo_bonetti.txt, Profile_Card/leonardo_bonetti/leonardo-bonetti.html
This Pull Request resolves Issue #14 and #1 
Description:
I added my profile.txt file and a profile_card made with HTML + CSS.
=> Added my profile.txt and my profile card

Fibonacci_Search/ashwathbhat.c
This Pull Request resolves Issue #19 
Description:
=> Fibonacci Search Added

ashwathbhat/XOR.c, ashwathbhat/circular.c, ashwathbhat/unrolled.c
This Pull Request resolves Issue #8 
Description:
=> Linked List Added

PARTICIPANTS/thanakorn-aum.txt
=> add detail user me

PARTICIPANTS/ppisut.txt
=> added new file ppisut.txt

Quick_Sort/quick_sort.c
=> Rename quicksort.c to quick_sort.c

Participants/NesChaiyapon.txt
**Description:**
- In this Pull Request we have done the following add NesChaiyapon.txt to folder Participants
=> Add my profile to folder Participants

Participants/krzysiekh.txt
=> User Description for krzysiekh added

C/kisabeary.c
*First Pull Request to Web Club NITK for Hacktoberfest 2k17 added!
*This Pull Request resolves Issue #3
=> add hello world

Hello_Web/kiszabeary.html
This Pull Request resolves Issue #22 
Description:
add kisabeary.html when clicked button display Hello World on tag p
=> add say hello web

Binary Search/Mukesh-BR.cpp
This Pull Request resolves Issue #25
Description:
=> Mukesh-BR Added details

Python/kiszabeary.py
Description:
add hello world in python
=> add hello world py

PARTICIPANTS/mbiagetti.txt
#1 Resolved
Description:
* Add me to the participant list!
=> Add Matteo Biagetti

Participants/codeSmart2307.txt
=> Added codeSmart2307.txt to Participants folder with details of myelf.

PARTICIPANTS/suleka96.txt
added a new text file to the PARTICIPANTS folder
=> added a new text file containing my details

Participants/jonatas.txt
Description:
Added new participant file with informations
=> Jonatas user description added

participants/renanpessoa.txt
First Pull Request to Web Club NITK for Hacktoberfest 2k17 added
=> User Description for renan pessoa added

C/hannahkriegler.c, Python/hannahkriegler.py
This Pull Request resolves Issue #11 #3 
Description:
added hello world in python
=> added helloWorld in Python

Reverse_String/incin.c
This Pull Request resolves Issue #9
Description:
In this Pull Request I have added clean, commented code for reversing a string.
=> Add string reverse implementation

PARTICIPANTS/faibz.txt
Added faibz.txt file into participants folder.
#1 resolved!
=> Added faibz.txt into participants folder.

Participants/akshat14714.txt
Description:
* Added the user description for akshat14714
=> User description for akshat14714 added

PARTICIPANTS/sidkapoor97.txt
=> sidkapoor97.txt added

Bubble Sort/Mukesh-BR-Bubble_sort.cpp
=> Mukesh Added details

Participants/wailay.txt
=> wailay.txt added

PARTICIPANTS/xicon73.txt
Hey There!
I'm Francisco and joining the fest!
Happy Hacktoberfest
=> added xicon73

Participants/riddhi.txt
First Pull Request to Web-Club NITK for Hacktoberfest2k17 added!
=> Added user description

reverse/Shivam.cpp
This Pull Request resolves Issue #9
=> Added reverse of string

C/anik08.cpp
=> c helloworld

Participants/udit-001.txt
=> Added contribution.

BinarySearch/anik08.cpp
binary search added on 16/10/17
This Pull Request resolves Issue #25 
Description:
=> binarysearch

BinarySearch/shanthanu9.py, reverse/shanthanu9.c
This Pull Request resolves Issue #9 #25  
Description:
=> Shanthanu9 added some details

Participants/enneakr.txt
=> User Description for enneakr added

Participants/Chinmay Patkar.txt
=> Chinmay-patkar

Participants/drac00l.txt
=> Added user description for drac00l

Insertion_Sort/shanthanu9.c
This Pull Request resolves Issue #13.
=> Insertion Sort added 

participants/xvaleriex.txt
=> Xvaleriex - Participant Details added!

Reverse_String/StringReverser.java
This Pull Request resolves Issue #9 
Description:
Added a Java class which asks for input text from the command line, prints it, then reverses it.
1. To compile:
javac Reverse_String/StringReverser.java
2. To run:
java Reverse_String/StringReverser
=> Implemented reversing a string in java

hello.rb
This Pull Request resolves Issue #464 
Description:
- Created Hello World in Ruby
=> Hello World in Ruby

Particpants/quatroka.txt
Description:
Added quatroka's profile in the participans folder.
=> Added profile quatroka

PARTICIPANTS/LazarusPolar.txt
Description:
- Added LazarusPolar.txt on the "Participants" Directory.
=> Added new .txt file on Participants directory

string/string.c
=> updated scanf

BubbleSort.c
=> adjusted ++ and included conio.h

Participants/worranut.txt, participants/worranut.txt
=> Move worranut.txt to Participants

Reverse_String/reverse.py
This Pull Request resolves Issue #9 
Description:
printing the string in reverse in python
=> Python program to reverse a string

Crash_em/crash_em.py
=> Hello Crash in Python

hello_world.c, python.py
This Pull Request resolves Issue #3 #429 
Description:
I have added a program to print Hello world! in C.
I am newbie in programming, please review it.
=> Added a program to Print Hello World!

Participants/mehnazyunus.txt, Quick_Sort/mehnazyunus.cpp
This Pull Request resolves Issue #24 #1 
Added participant description
=> added quicksort

Participants/rm-1612.txt
=> User Description for rm-1612 added

Linear_search/Linear_search.cpp
Language used c++.
This Pull Request resolves Issue #425 
Description:
In this, I added linear_search implementation in c++ language.
please review this and if any error or any correction is there, i will resolve it.
=> Added linear search.

PARTICIPANTS/odzeno.txt
=> Add odzeno

Quick_Sort/RosaGeorge31.c, sieve_of_erastothenes/RosaGeorge31.py
This Pull Request resolves Issue #17 
Description:
Sieve of Erastothenes
=> Sieve of Erastothenes added 

Participants/qservando.txt
Updated to correct directory. Thank you. #1
=> Updated Participants

GUI_Calculator/rkpattnaik780/JSCalculator/calculator.css, GUI_Calculator/rkpattnaik780/JSCalculator/compute.js, GUI_Calculator/rkpattnaik780/JSCalculator/index.html, GUI_Calculator/rkpattnaik780/README.md
This Pull Request resolves Issue #26
=> A calculator using html , css and javascript

GUI_Calculator/shareWithMeCalc/calculator.py
This Pull Request resolves Issue #26 
Description:
I have made use of Tkinter module in python to build a simple calculator.
=> Adding a GUI based calculator using python and Tkinter

Hello_Web/share-with-me.html
This Pull Request resolves Issue #22 
Description:
This PR follows the steps as mentioned. Displays a 'Hello World' text on the webpage when the button is clicked.
=> Hello World displayed on webpage on button click

Linear_search/linearSearch.c
This Pull Request resolves Issue #412 
Description:
This PR implements a linear search in C language.
=> Linear Search in C

Quick_Sort/vartika-arora.c, vartika-arora/sieve_of_erastothenes.py
This Pull Request resolves Issue #24 #31
=> Added Quick_Sort

BubbleSort/wilson8507.py, Participants/qservando.txt
Description:
- added BubbleSort Algorithm
=> Added bubble sort

Fibonacci_Search/vartika-arora.c
This Pull Request resolves Issue #19
=> Added Fibonacci Search

Participants/Loveiswar.txt
=> Add about Ankur

Binary Search/Prajnaaa12.java, Bitwise Operators/Prajnaaa12.c, C/helloworld.c
This Pull Request resolves Issue #3 #28 #25
=> Hello world

Binary Search/Prajnaaa12.java, Bitwise Operators/Prajnaaa12.c
This Pull Request resolves Issue #28 
Description:
=> Bitwise operators implemented in c

python/krahulreddy.py
cc @salman-bhai
Description:
In this Pull Request I added Hello World in python.
=> Added hello world in python

Participants/NishantKr97.txt
=> Participants Folder added

Insertion_Sort/NishantKr97.c, Participants/NishantKr97.txt
This Pull Request resolves Issue #13
=> Insertionsort

Participants/himanscience.txt
First pull request to WebClub-NITK
=> User description for himanscience.

Bitwise Operator/ShreyasheeS.cpp, Bitwise Operator/ShreyasheeS2.cpp
This Pull Request resolves Issue #28
=> Added a code to swap bits in an integer

Bitwise Operator/ShreyasheeS.cpp
This Pull Request resolves Issue #28
=> Added ShreyasheeS.cpp to Bitwise Operator

Ruby/hello.rb
This Pull Request resolves Issue #464 
Description:
Changes: Add Ruby directory and a file Hello.rb in it.
The file includes the program Hello World in Ruby.
=> Add Hello World in Ruby

C/alxPgns.c
=> My Hello World

Bucket-sort.py, PHPmailer.php
This Pull Request resolves Issue #457  and #551 
Description:
In this Pull Request Bucket Sort in Python is added and also an Example for PHP mailer is added.
=> Bucket Sort In Python and PHP mailer 

GUI_Calculator/ampmail1998/Calculator.java
This Pull Request resolves Issue #26 
Description:
=> Added GUI calculator using Java Swing

Participants/LorisZ.txt
Description:
Added Participant LorisZ Details for the Hacktoberfest Repository Contributors
=> Add Participant Details for the Hacktoberfest Repository Contributors

Binary Search/Prajnaaa12.java, Bitwise Operators/Prajnaaa12.c
This Pull Request resolves Issue #25 
Description:
=> Binary search

Binary Search/Prajnaaa12.java, Bitwise Operators/Prajnaaa12.c, Bubble Sort/Prajnaa.c
This Pull Request resolves Issue #27
Description:
=> Bubble sort

Insertion_Sort/doubledare704.py
Description:
added python variant for insertion sort
=> added python isertion sort

Participants/smarty1palak.txt
Description:
this pull request contains my details.
=> added participant details

Insertion_Sort/smarty1palak.c
Description:
In this Pull Request i have added the program for insertion sort
=> created insertion sort.c

Merge_Sort/smarty1palak.c, Quick_Sort/smarty1palak.c, linear_search/smarty1palak.c
Description:
In this Pull Request i have added the code for quick sort
=> created quick_sort.c

C/wombatlover.c, Python/wombatlover.py
Description:
Using a branch
Add: #3 Hello World in C
=> Add: #3 Hello World in C

C/wombatlover.c, Python/wombatlover.py
Description:
Add Hello World Python script
=> Add: #11 Hello World Python script

GUI_Calculator/NVS16/css/main.css, GUI_Calculator/NVS16/index.html, GUI_Calculator/NVS16/js/main.js, Participants/NVS16.txt
This Pull Request resolves Issue #26 #1 
Description:
In this Pull Request I have done the following additions/edits for the code:
-> Added a basic GUI_Calculator using HTML, CSS, JS and BOOTSTRAP.
=> Added GUI_CALCULATOR (HTML,CSS,JS,BOOTSTRAP)

Python/sambhav2612.py
=> added new file for issue #11

Bitwise Operator/sambhav2612.cpp
by user: sambhav2612
This Pull Request resolves Issue #28
=> added file for issue #28

C/sambhav2612.c
This Pull Request adds a file for Issue #3 for user: sambhav2612 // under C dir
=> Proposing new file for issue #3

Participants/SambhavJain.txt
in participants directory
Issue #1
=> Added file for user: sambhav2612

BinarySearch/sambhav2612.c
This Pull Request resolves Issue #25
=> added file for issue #25

Participants/ecwolf.txt, Python/ecwolf.py
This Pull Request resolves Issue #1 #11
=> User Description for ecwolf added

Participants/ankitjena.txt
=> User description for ankitjena added

C/emmetmayer.c
Description:
Using a branch
Add: #3 Hello World in C
=> Adding my hello.c

Participants/arunvm.txt
=> added details

C/supamas.c
=> add supamas.c

PARTICIPANTS/alator21.txt, Participants/alator21.txt
=> Added my name

sieve_of_erastothenes/smarty1palak.c
This Pull Request resolves Issue #17 
Description:
In this Pull Request i have written the code to implement sieve of erastothenes
=> added sieve of erastothenes

HELLO_WORLD.pas
This Pull Request resolves Issue #552 
Changes: Add File HELLO_WORLD.pas
=> HelloWorld in Pascal

PARTICIPANTS/sttsk.txt, Participants/sttsk.txt, Python/sttsk.py
Added Python/sttsk.py and Participants/sttsk.txt for the User Description.
=> Add Hello World in Python

Fibonacci_Search/Fibonacci_php.php
=> adding implement fibonacci search in php

Python/lovish318.py
Description:
To print hello world in python
=> program to print hello world in python

Python/Kinshuk191999.py
Description:
Program for beginners to print Hello World in python
=> Program for beginners to print Hello World in python

C/NVS16.c
Description:
-> Added hello world program in C
=> Added Hello World Program

C/mani995.c
Description:
Program for beginner to print hello in c
=> Program for beginner to print hello in c 

C/mani995.c, Python/mani995.py
Description:
Program to print hello in python
=> Program to print hello in python

PARTICIPANTS/eliassilva8.txt
Description:
Add Elias Silva to PARTICIPANTS
=> User Description for elias-silva added

Bitwise Operator/kul96.c, C/kul96.c, Insertion_Sort/kul96.c, Merge_Sort/kul96.c, Participants/kuldeep.txt, Python/kul96.py
This Pull Request resolves Issue #23 
Description:
=> Kul patch 3

Bitwise Operator/kul96.c, C/kul96.c, Insertion_Sort/kul96.c, Participants/kuldeep.txt
=> Kul patch 1

Bitwise Operator/kul96.c, C/kul96.c, Insertion_Sort/kul96.c, Participants/kuldeep.txt, Python/kul96.py
=> Kul patch 2

Mergesort.c, insertion_sort/insert.c, participants/vibha.txt, reverse.c
=> Merge Sort Added

Participants/jobizzz.txt
=> FOurth Commit

PARTICIPANTS/bellsenawat.txt
First PR to web club NITK for Hacktoberfest 2017 added 
Referenced #1
=> Add my profile bellsenawat

Participants/adkdev.txt
=> Add adkdev to Participants

C/ohmcoe.c
=> add hello world(ohmcoe)

Python/chironly.py
Description:
Created Hello World Program in Python
=> Add: Python Hello World #11

Bubble_Sort/adarshj17.c, Bubble_Sort/sisgandarli.c
Now, time complexity is at most N^2.
=> Changed the bubble sort to more optimized version.

towerofhanoi/DhvanilP.py
=> Tower of Hanoi added

BinarySearchCS/RecursiveBinarySearch
=> Added binary search in C#

Binary Search/binarysearch.c
make a function of binary_search rather than to implement in void main
This Pull Request resolves Issue #25 
Description:
Binary Search added!
=> binary_search.c

Insertion_Sort/HrushikeshChoudhary.cs
Description:
Added insertion sort in C#
@MJ10 @salman-bhai
=> Added insertion sort in C#

PARTICIPANTS/mayankk98.txt
=>  user description for mayankk98 added

bubble_sort/bubble_sort.c
=> Implementing based on Bubble Sort Algorithm

PARTICIPANTS/blacksource.txt
=> add my name

Factorial_program/Factorial_Program.py
Factorial program in python language
#752
=> Factorial Program

participants/aritra24.txt
=> Added name.txt file

PARTICIPANTS/montitawi.txt
First Pull Request
#1 resolved
=> User Description 

PARTICIPANTS/chennakeshava.txt
Adding file having name and other details in Participants directory 
#1 Issue  - Add Participant Details
=> adding intro file in PARTICIPANTS

HTTP_Server_Golang/ReadMe.md, HTTP_Server_Golang/app.go, Participants/ekamwalia.txt
This Pull Request resolves Issue #765 
Description:
Added the code to setup an HTTP server using Go
=> Simple HTTP Server using Go

Hello AWK/Sudhanshu36.awk
This Pull Request resolves Issue #806
=> Hello world in AWK language

kruskal_algorithm/HrushikeshChoudhary.java
This Pull Request resolves Issue #817 
Description:
Added implementation of Kruskal's algorithm in java
Please review @salman-bhai
=> Added Kruskals algorithm in java

participants/kevin.txt
=> add participant Kevin Madison

Participants/jtownsley.txt
Description:
In this Pull Request I have added my introduction file to the participants folder
=> Add my participant file

floyds_algorithm/HrushikeshChoudhary.java
This Pull Request resolves Issue #825 
Description:
Added the Implementation of All-Pairs Shortest Paths problem using Floyd's algorithm in java.
Please review @salman-bhai @MJ10
=> Added floyd's algorithm in java

PARTICIPANTS/sakshi7896.txt
=> User Description for sakshi7896 added

PARTICIPANTS/ssaabye.txt
Added text file with my information to participants folder
Resolved #1
=> Added ssaabye.txt

Longest Increasing Subsequence/longestIncreasingSubsequence.cpp, MajorityElementOfArray/MajorityElement.cpp, PARTICIPANTS/darkHorse.txt, SubSetGenerator/subset_generator.cpp
- Participant file
- Subset Generator Code
- Majority Element Code
- Longest Increasing Subsequence Code
#1
=> Participant file, Subset Gen Code, Majority Element Code, LIS code added

PARTICIPANTS/nikhilatmaple.txt, participants/niks.md
Added my profile under the PARTICIPANTS directory for HACKTOBERFEST!
=> Added profile under PARTICIPANTS
